Add new unenrollment exploit
3kh0/ext-remover pull request #1198
Opened 2024-10-22 02:13 UTC by schoolexploitkid

Add new unenrollment exploit (OlyBmmer)

2024-10-23 02:57 UTC, Byteeeeeeee commented
add crsh2tty aswell

2024-10-23 22:40 UTC, 3kh0 requested changes
Please add the section to the table of contents

2024-10-23 23:25 UTC, schoolexploitkid commented
srry forgot lemme do rn

2024-10-23 23:29 UTC, schoolexploitkid commented
table of contents added

2024-10-27 02:12 UTC, 3kh0 approved these changes
Thank you

2024-10-27 02:12 UTC, merged