Update README.md
3kh0/ext-remover pull request #830
Opened 2023-11-29 00:45 UTC by Ender-Ghost-Craft

2023-11-29 00:59 UTC, 3kh0 requested changes
It is better to add this to the skiovox exploit

2023-11-29 01:40 UTC, Ender-Ghost-Craft commented
maybe add it to both? people might not remember and it will help anybody who does both

2023-11-29 02:31 UTC, 3kh0 commented
A powerwash means that you reset the Chromebook, you remove all* data on it, I think that should be a given honestly

2023-12-07 16:59 UTC, Hilololsusy commented
Honestly, I think if someone knows how to powerwash a chromebook, they know what it does.

2023-12-07 17:44 UTC, closed without merging